import { initializeApp, getApps } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { getAuth, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import { getFirestore, collection, doc, setDoc, addDoc, deleteDoc, onSnapshot, query, orderBy, serverTimestamp, runTransaction, getDoc } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import { firebaseConfig, ADMIN_EMAIL } from "./firebase-config.js";

const app = getApps().find(a=>a.name==='[DEFAULT]') || initializeApp(firebaseConfig);
const auth=getAuth(app), db=getFirestore(app);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>`Rs. ${Number(n||0).toLocaleString('en-LK')}`;
const todayKey=(d=new Date())=>{const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)};
const defaults={products:[],sales:[],settings:{storeName:'KB LABEL',phone:'+94 77 000 0000',address:'Sri Lanka',footer:'Thank you for shopping with KB Label.',printer:'80mm'}};
let state=structuredClone(defaults),cart=[],activeCategory='All',ready=false;
function toast(msg,type='ok'){const el=$('#toast');if(!el)return;el.textContent=msg;el.className=`toast show ${type==='error'?'error':''}`;setTimeout(()=>el.classList.remove('show'),2400)}
function requireAdmin(){const u=auth.currentUser;if(!u||u.email?.toLowerCase()!==ADMIN_EMAIL.toLowerCase())throw new Error('Admin login required.');return u}
function normalizeProduct(snap){const d=snap.data()||{};return {id:snap.id,name:d.name||'Untitled Product',sku:d.sku||d.barcode||`KB-${snap.id.slice(0,6).toUpperCase()}`,category:d.category||'T-Shirt',size:d.size||((d.sizes||[]).join(', ')),color:d.color||((d.colors||[]).join(', ')),price:Number(d.discountEnabled&&d.discountPrice?d.discountPrice:d.price||0),cost:Number(d.cost||d.buyingPrice||0),stock:Number(d.stockQty??d.quantity??(d.stockStatus==='out-of-stock'?0:10)),image:d.image||'',description:d.description||'',stockStatus:d.stockStatus||'in-stock'} }
function normalizeSale(snap){const d=snap.data()||{};const date=d.date?.toDate?.()?.toISOString?.()||d.date||new Date().toISOString();return {id:snap.id,...d,date}}

const viewMeta={dashboard:['OVERVIEW','Dashboard'],pos:['POINT OF SALE','New Sale'],products:['INVENTORY','Products'],sales:['TRANSACTIONS','Sales History'],reports:['ANALYTICS','Reports'],barcodes:['PRODUCT TAGGING','Barcodes & Labels'],settings:['SYSTEM','Settings']};
function switchView(name){$$('.view').forEach(v=>v.classList.remove('active'));$(`#${name}View`)?.classList.add('active');$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#pageEyebrow').textContent=viewMeta[name][0];$('#pageTitle').textContent=viewMeta[name][1];$('#sidebar').classList.remove('open');({dashboard:renderDashboard,pos:renderPOS,products:renderProducts,sales:renderSales,reports:renderReports,barcodes:renderBarcodes,settings:renderSettings}[name])?.()}
$$('.nav-item').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-view-jump]').forEach(b=>b.onclick=()=>switchView(b.dataset.viewJump));$$('[data-open-pos]').forEach(b=>b.onclick=()=>switchView('pos'));$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');

function renderDashboard(){const now=todayKey(),todaySales=state.sales.filter(s=>todayKey(s.date)===now),todayRevenue=todaySales.reduce((a,s)=>a+Number(s.total||0),0),totalRevenue=state.sales.reduce((a,s)=>a+Number(s.total||0),0),totalUnits=state.products.reduce((a,p)=>a+p.stock,0),low=state.products.filter(p=>p.stock<=5).length;$('#statTodayRevenue').textContent=money(todayRevenue);$('#statTodayOrders').textContent=`${todaySales.length} orders`;$('#statTotalRevenue').textContent=money(totalRevenue);$('#statProducts').textContent=state.products.length;$('#statUnits').textContent=`${totalUnits} units in stock`;$('#statLowStock').textContent=low;$('#heroSales').textContent=money(todayRevenue);$('#heroLowStock').textContent=`${low} items`;const days=[...Array(7)].map((_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));return d}),values=days.map(d=>state.sales.filter(s=>todayKey(s.date)===todayKey(d)).reduce((a,s)=>a+Number(s.total||0),0)),max=Math.max(...values,1);$('#salesChart').innerHTML=days.map((d,i)=>`<div class="bar-item"><div class="bar" data-value="${money(values[i])}" style="height:${Math.max(8,values[i]/max*190)}px"></div><div class="bar-label">${d.toLocaleDateString('en-US',{weekday:'short'})}</div></div>`).join('');$('#recentSalesList').innerHTML=state.sales.slice(0,5).map(s=>`<div class="list-row"><div><strong>${s.receipt}</strong><span>${s.customerName||'Walk-in customer'} · ${new Date(s.date).toLocaleDateString()}</span></div><strong>${money(s.total)}</strong></div>`).join('')||'<div class="empty-state">No sales yet</div>'}
function categories(){return ['All',...new Set(state.products.map(p=>p.category))]}
function renderPOS(){const q=$('#posSearch').value.toLowerCase();$('#categoryChips').innerHTML=categories().map(c=>`<button class="chip ${c===activeCategory?'active':''}" data-cat="${c}">${c}</button>`).join('');$$('#categoryChips .chip').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.cat;renderPOS()});const f=state.products.filter(p=>(activeCategory==='All'||p.category===activeCategory)&&`${p.name} ${p.sku} ${p.category}`.toLowerCase().includes(q));$('#posProductGrid').innerHTML=f.map(p=>`<article class="product-card ${p.stock<=0?'out':''}" data-add-product="${p.id}"><div class="product-image">${p.image?`<img src="${p.image}" alt="">`:`<div class="placeholder">${p.name.slice(0,2).toUpperCase()}</div>`}</div><h4>${p.name}</h4><p>${p.size||'-'} · ${p.color||'-'} · ${p.sku}</p><div class="product-card-footer"><strong>${money(p.price)}</strong><span class="stock-badge ${p.stock<=5?'low':''}">${p.stock} left</span></div></article>`).join('')||'<div class="empty-state">No matching products</div>';$$('[data-add-product]').forEach(c=>c.onclick=()=>addToCart(c.dataset.addProduct));renderCart()}
$('#posSearch').oninput=renderPOS;
function addToCart(id){const p=state.products.find(x=>x.id===id);if(!p||p.stock<=0)return toast('Out of stock','error');const r=cart.find(x=>x.id===id);if(r){if(r.qty>=p.stock)return toast('Not enough stock','error');r.qty++}else cart.push({...p,qty:1});renderCart();const bi=$('#barcodeInput');if(bi){bi.value='';bi.focus({preventScroll:true})}}
function renderCart(){$('#cartItems').innerHTML=cart.map(i=>`<div class="cart-row"><div><h4>${i.name}</h4><small>${i.size||'-'} · ${i.color||'-'} · ${money(i.price)}</small><button class="remove-cart" data-remove="${i.id}">Remove</button></div><div class="qty-control"><button data-dec="${i.id}">−</button><strong>${i.qty}</strong><button data-inc="${i.id}">+</button></div></div>`).join('')||'<div class="empty-state">Your cart is empty</div>';$$('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.id!==b.dataset.remove);renderCart()});$$('[data-dec]').forEach(b=>b.onclick=()=>{const x=cart.find(i=>i.id===b.dataset.dec);x.qty--;if(x.qty<=0)cart=cart.filter(i=>i.id!==x.id);renderCart()});$$('[data-inc]').forEach(b=>b.onclick=()=>{const x=cart.find(i=>i.id===b.dataset.inc),p=state.products.find(i=>i.id===x.id);if(x.qty>=p.stock)return toast('Not enough stock','error');x.qty++;renderCart()});updateTotals()}
function totals(){const subtotal=cart.reduce((a,i)=>a+i.price*i.qty,0),d=Number($('#discountInput').value||0),discount=$('#discountType').value==='percent'?Math.min(subtotal,subtotal*d/100):Math.min(subtotal,d);return{subtotal,discount,total:Math.max(0,subtotal-discount)}}
function updateTotals(){const t=totals();$('#subtotalText').textContent=money(t.subtotal);$('#totalText').textContent=money(t.total);const received=Number($('#cashReceived')?.value||0);if($('#changeText'))$('#changeText').textContent=money(Math.max(0,received-t.total));}$('#discountInput').oninput=updateTotals;$('#discountType').onchange=updateTotals;$('#cashReceived').oninput=updateTotals;$('#paymentMethod').onchange=()=>{$('#cashReceivedWrap').style.display=$('#paymentMethod').value==='Cash'?'grid':'none';updateTotals()};$('#clearCart').onclick=()=>{cart=[];renderCart()};
async function saveCurrentSale(cashReceived=0){if(!cart.length){toast('Add at least one product','error');return false}const btn=$('#completeSale');btn.disabled=true;btn.textContent='Saving...';try{requireAdmin();const t=totals(),receipt=`KB-${Date.now().toString().slice(-8)}`,payment=$('#paymentMethod').value;if(payment==='Cash'&&Number(cashReceived)<t.total)throw new Error('Cash received is less than the bill total.');const sale={receipt,date:new Date().toISOString(),customerName:$('#customerName').value.trim(),customerPhone:$('#customerPhone').value.trim(),items:cart.map(x=>({id:x.id,name:x.name,sku:x.sku,size:x.size,color:x.color,price:x.price,qty:x.qty})),subtotal:t.subtotal,discount:t.discount,total:t.total,payment,cashReceived:Number(cashReceived||0),change:payment==='Cash'?Math.max(0,Number(cashReceived)-t.total):0,source:'pos',createdAt:serverTimestamp()};await runTransaction(db,async tx=>{for(const i of sale.items){const ref=doc(db,'products',i.id),snap=await tx.get(ref);if(!snap.exists())throw new Error(`${i.name} no longer exists.`);const d=snap.data(),stock=Number(d.stockQty??d.quantity??(d.stockStatus==='out-of-stock'?0:10));if(stock<i.qty)throw new Error(`${i.name}: only ${stock} left.`);const next=stock-i.qty;tx.update(ref,{stockQty:next,quantity:next,stockStatus:next<=0?'out-of-stock':'in-stock',updatedAt:serverTimestamp()})}const saleRef=doc(collection(db,'posSales'));tx.set(saleRef,sale)});showReceipt({...sale,id:receipt});cart=[];$('#customerName').value='';$('#customerPhone').value='';$('#discountInput').value=0;$('#cashReceived').value='';renderCart();toast('Sale completed');if($('#autoPrint')?.checked)setTimeout(()=>printReceiptDocument({...sale,id:receipt}),250);return true}catch(e){console.error(e);toast(e.message||'Sale failed','error');return false}finally{btn.disabled=false;btn.textContent='F9 · Complete & Print'}}
function openCashDrawer(){if(!cart.length)return toast('Add at least one product','error');const t=totals();$('#cashDueText').textContent=money(t.total);$('#cashModalReceived').value=$('#cashReceived').value||'';$('#cashModalChange').textContent=money(Math.max(0,Number($('#cashModalReceived').value||0)-t.total));const notes=[t.total,Math.ceil(t.total/100)*100,Math.ceil(t.total/500)*500,Math.ceil(t.total/1000)*1000].filter((v,i,a)=>v>0&&a.indexOf(v)===i);$('#quickCashButtons').innerHTML=notes.map(v=>`<button type="button" data-cash="${v}">${money(v)}</button>`).join('');$$('[data-cash]').forEach(b=>b.onclick=()=>{$('#cashModalReceived').value=b.dataset.cash;updateCashChange()});$('#cashModal').classList.add('open');setTimeout(()=>$('#cashModalReceived').focus(),80)}
function updateCashChange(){const t=totals(),v=Number($('#cashModalReceived').value||0);$('#cashModalChange').textContent=money(Math.max(0,v-t.total))}
$('#cashModalReceived').oninput=updateCashChange;$('#closeCashModal').onclick=()=>$('#cashModal').classList.remove('open');$('#confirmCashSale').onclick=async()=>{if(await saveCurrentSale(Number($('#cashModalReceived').value||0)))$('#cashModal').classList.remove('open')};
$('#completeSale').onclick=()=>$('#paymentMethod').value==='Cash'?openCashDrawer():saveCurrentSale(0);
function escapeReceiptText(value){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]))}
function receiptHTML(s){const set=state.settings;return `<img src="store-logo.webp" alt="KB Label"><h2>${escapeReceiptText(set.storeName)}</h2><div class="receipt-sub">${escapeReceiptText(set.address)}<br>${escapeReceiptText(set.phone)}</div><div class="receipt-line"></div><div class="receipt-row"><span>Receipt</span><strong>${escapeReceiptText(s.receipt)}</strong></div><div class="receipt-row"><span>Date</span><span>${escapeReceiptText(new Date(s.date).toLocaleString())}</span></div><div class="receipt-row"><span>Customer</span><span>${escapeReceiptText(s.customerName||'Walk-in')}</span></div><div class="receipt-line"></div>${(s.items||[]).map(i=>`<div class="receipt-row"><span>${escapeReceiptText(i.name)} x${Number(i.qty||0)}<br><small>${escapeReceiptText(i.size||'')} ${escapeReceiptText(i.color||'')}</small></span><span>${money(Number(i.price||0)*Number(i.qty||0))}</span></div>`).join('')}<div class="receipt-line"></div><div class="receipt-row"><span>Subtotal</span><span>${money(s.subtotal)}</span></div><div class="receipt-row"><span>Discount</span><span>${money(s.discount)}</span></div><div class="receipt-row receipt-total"><span>TOTAL</span><span>${money(s.total)}</span></div><div class="receipt-row"><span>Payment</span><span>${escapeReceiptText(s.payment)}</span></div>${s.payment==='Cash'?`<div class="receipt-row"><span>Cash</span><span>${money(s.cashReceived)}</span></div><div class="receipt-row"><span>Change</span><strong>${money(s.change)}</strong></div>`:''}<div class="receipt-line"></div><div class="receipt-sub">${escapeReceiptText(set.footer)}</div>`}
let activeReceipt=null;
function showReceipt(s){activeReceipt=s;$('#receiptPreview').innerHTML=receiptHTML(s);$('#receiptModal').classList.add('open')}
function printReceiptDocument(s=activeReceipt){
  if(!s){toast('No receipt selected','error');return}
  const width=state.settings.printer==='58mm'?'58mm':state.settings.printer==='A4'?'210mm':'80mm';
  const pageMargin=state.settings.printer==='A4'?'14mm':'3mm';
  const frame=document.createElement('iframe');
  frame.setAttribute('aria-hidden','true');
  frame.style.cssText='position:fixed;right:0;bottom:0;width:0;height:0;border:0;visibility:hidden';
  document.body.appendChild(frame);
  const docu=frame.contentWindow.document;
  docu.open();
  docu.write(`<!doctype html><html><head><meta charset="utf-8"><title>${escapeReceiptText(s.receipt||'KB Label Receipt')}</title><style>@page{size:${width} auto;margin:${pageMargin}}*{box-sizing:border-box}html,body{margin:0;padding:0;background:#fff;color:#000;font-family:"Courier New",monospace;-webkit-print-color-adjust:exact;print-color-adjust:exact}.receipt{width:100%;max-width:${width};margin:0 auto;padding:${state.settings.printer==='A4'?'8mm':'1mm'};font-size:${state.settings.printer==='58mm'?'10px':'12px'};line-height:1.35}.receipt img{display:block;max-width:${state.settings.printer==='58mm'?'25mm':'32mm'};max-height:20mm;object-fit:contain;margin:0 auto 2mm}.receipt h2{text-align:center;margin:0 0 1mm;font-size:${state.settings.printer==='58mm'?'16px':'20px'}}.receipt-sub{text-align:center;font-size:.9em}.receipt-line{border-top:1px dashed #000;margin:2.5mm 0}.receipt-row{display:flex;justify-content:space-between;align-items:flex-start;gap:3mm;margin:1.4mm 0}.receipt-row>span:first-child{flex:1;min-width:0}.receipt-row>span:last-child,.receipt-row>strong:last-child{text-align:right;white-space:nowrap}.receipt-total{font-size:1.25em;font-weight:800;margin-top:2mm}.receipt small{font-size:.82em} @media print{html,body{width:${width}}}</style></head><body><main class="receipt">${receiptHTML(s)}</main></body></html>`);
  docu.close();
  const runPrint=()=>{try{frame.contentWindow.focus();frame.contentWindow.print()}catch(e){console.error(e);toast('Print preview could not open','error')}finally{setTimeout(()=>frame.remove(),1800)}};
  const images=[...docu.images];
  if(!images.length) setTimeout(runPrint,120);
  else Promise.all(images.map(img=>img.complete?Promise.resolve():new Promise(resolve=>{img.onload=resolve;img.onerror=resolve}))).then(()=>setTimeout(runPrint,120));
}
$('#printReceiptBtn').onclick=()=>printReceiptDocument();$$('[data-close-receipt]').forEach(b=>b.onclick=()=>$('#receiptModal').classList.remove('open'));
function productStatus(p){if(p.stock<=0)return['Out of stock','out'];if(p.stock<=5)return['Low stock','low'];return['In stock','']}
function renderProducts(){const q=$('#productSearch').value.toLowerCase(),rows=state.products.filter(p=>`${p.name} ${p.sku} ${p.category} ${p.size} ${p.color}`.toLowerCase().includes(q));$('#productsTableBody').innerHTML=rows.map(p=>{const st=productStatus(p);return `<tr><td class="product-select-cell"><input class="product-label-check" type="checkbox" value="${p.id}"></td><td><div class="table-product"><div class="table-thumb">${p.image?`<img src="${p.image}">`:p.name.slice(0,2).toUpperCase()}</div><div><strong>${p.name}</strong><br><small>${p.description||''}</small></div></div></td><td>${p.sku}</td><td>${p.category}</td><td>${p.size||'-'} / ${p.color||'-'}</td><td>${money(p.price)}</td><td><input class="inline-stock" type="number" min="0" value="${p.stock}" data-stock-id="${p.id}" aria-label="Stock for ${p.name}"></td><td><span class="status ${st[1]}">${st[0]}</span></td><td><div class="row-actions"><button data-label="${p.id}">Label</button><button data-edit="${p.id}">Edit</button><button data-delete="${p.id}">Delete</button></div></td></tr>`}).join('')||'<tr><td colspan="9"><div class="empty-state">No products found</div></td></tr>';$$('[data-edit]').forEach(b=>b.onclick=()=>openProductModal(b.dataset.edit));$$('[data-delete]').forEach(b=>b.onclick=()=>deleteProduct(b.dataset.delete));$$('[data-label]').forEach(b=>b.onclick=()=>{switchView('barcodes');$('#labelProductSelect').value=b.dataset.label;syncLabelPreview()});$$('[data-stock-id]').forEach(input=>{input.onchange=async()=>{const value=Math.max(0,Number(input.value||0));input.classList.add('stock-saving');try{requireAdmin();await setDoc(doc(db,'products',input.dataset.stockId),{stockQty:value,quantity:value,stockStatus:value<=0?'out-of-stock':'in-stock',updatedAt:serverTimestamp()},{merge:true});toast('Stock updated')}catch(e){toast(e.message,'error')}finally{input.classList.remove('stock-saving')}}})} 
$('#productSearch').oninput=renderProducts;$('#addProductBtn').onclick=()=>openProductModal();function openProductModal(id=''){const p=state.products.find(x=>x.id===id);$('#productModalTitle').textContent=p?'Edit Product':'Add Product';$('#productId').value=p?.id||'';$('#productName').value=p?.name||'';$('#productSku').value=p?.sku||'';$('#productCategory').value=p?.category||'T-Shirt';$('#productSize').value=p?.size||'';$('#productColor').value=p?.color||'';$('#productPrice').value=p?.price||'';$('#productCost').value=p?.cost||0;$('#productStock').value=p?.stock??0;$('#productImage').value=p?.image||'';$('#productDescription').value=p?.description||'';$('#productModal').classList.add('open')}$$('[data-close-modal]').forEach(b=>b.onclick=()=>$('#productModal').classList.remove('open'));
$('#productForm').onsubmit=async e=>{e.preventDefault();try{requireAdmin();const id=$('#productId').value,ref=id?doc(db,'products',id):doc(collection(db,'products')),stock=Number($('#productStock').value),data={name:$('#productName').value.trim(),sku:$('#productSku').value.trim(),barcode:$('#productSku').value.trim(),category:$('#productCategory').value,size:$('#productSize').value.trim(),color:$('#productColor').value.trim(),sizes:$('#productSize').value.split(',').map(x=>x.trim()).filter(Boolean),colors:$('#productColor').value.split(',').map(x=>x.trim()).filter(Boolean),price:Number($('#productPrice').value),cost:Number($('#productCost').value),stockQty:stock,quantity:stock,stockStatus:stock<=0?'out-of-stock':'in-stock',image:$('#productImage').value.trim(),description:$('#productDescription').value.trim(),active:true,updatedAt:serverTimestamp()};if(!id)data.createdAt=serverTimestamp();await setDoc(ref,data,{merge:true});$('#productModal').classList.remove('open');toast('Product saved to Firebase')}catch(err){toast(err.message||'Product save failed','error')}};
async function deleteProduct(id){if(!confirm('Delete this product from Firebase?'))return;try{requireAdmin();await deleteDoc(doc(db,'products',id));toast('Product deleted')}catch(e){toast(e.message||'Delete failed','error')}}
function renderSales(){const q=$('#salesSearch').value.toLowerCase(),rows=state.sales.filter(s=>`${s.receipt} ${s.customerName} ${s.payment}`.toLowerCase().includes(q));$('#salesTableBody').innerHTML=rows.map(s=>`<tr><td><strong>${s.receipt}</strong></td><td>${new Date(s.date).toLocaleString()}</td><td>${s.customerName||'Walk-in'}<br><small>${s.customerPhone||''}</small></td><td>${(s.items||[]).reduce((a,i)=>a+i.qty,0)}</td><td>${s.payment}</td><td><strong>${money(s.total)}</strong></td><td><div class="row-actions"><button data-reprint="${s.id}">Print</button><button data-sale-delete="${s.id}">Delete</button></div></td></tr>`).join('')||'<tr><td colspan="7"><div class="empty-state">No sales yet</div></td></tr>';$$('[data-reprint]').forEach(b=>b.onclick=()=>showReceipt(state.sales.find(s=>s.id===b.dataset.reprint)));$$('[data-sale-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this sale record? Stock will not be restored.'))return;await deleteDoc(doc(db,'posSales',b.dataset.saleDelete));toast('Sale deleted')})}$('#salesSearch').oninput=renderSales;
function renderReports(){const gross=state.sales.reduce((a,s)=>a+Number(s.subtotal||0),0),discount=state.sales.reduce((a,s)=>a+Number(s.discount||0),0),net=state.sales.reduce((a,s)=>a+Number(s.total||0),0),items=state.sales.reduce((a,s)=>a+(s.items||[]).reduce((x,i)=>x+i.qty,0),0);$('#reportGross').textContent=money(gross);$('#reportDiscounts').textContent=money(discount);$('#reportNet').textContent=money(net);$('#reportItems').textContent=items;const counts={};state.sales.forEach(s=>(s.items||[]).forEach(i=>counts[i.name]=(counts[i.name]||0)+i.qty));$('#topProducts').innerHTML=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,6).map(([name,qty],i)=>`<div class="rank-row"><div><strong>#${i+1} ${name}</strong><span>${qty} units sold</span></div><strong>${qty}</strong></div>`).join('')||'<div class="empty-state">No sales data</div>';const pays={Cash:0,Card:0,'Bank Transfer':0};state.sales.forEach(s=>pays[s.payment]=(pays[s.payment]||0)+Number(s.total||0));const max=Math.max(...Object.values(pays),1);$('#paymentMix').innerHTML=Object.entries(pays).map(([k,v])=>`<div class="pay-row"><span>${k}</span><div class="progress"><i style="width:${v/max*100}%"></i></div><strong>${money(v)}</strong></div>`).join('')}

function generateBarcode(){const prefix='200';const body=String(Date.now()).slice(-9);return prefix+body}
function productTagHTML(p){return `<div class="product-tag"><div class="tag-brand">KB LABEL</div><div class="tag-name">${p.name}</div><svg class="barcode-svg" data-code="${p.sku}"></svg><div class="tag-meta"><span>${p.size||p.category||''}</span><strong>${money(p.price)}</strong></div></div>`}
function drawBarcodes(root=document){root.querySelectorAll('.barcode-svg').forEach(svg=>{try{JsBarcode(svg,svg.dataset.code,{format:'CODE128',displayValue:true,fontSize:12,height:42,margin:2})}catch(e){svg.outerHTML='<small>Invalid barcode</small>'}})}
function renderBarcodes(){const sel=$('#labelProductSelect');if(!sel)return;const current=sel.value;sel.innerHTML=state.products.map(p=>`<option value="${p.id}">${p.name} — ${p.sku}</option>`).join('');if(state.products.some(p=>p.id===current))sel.value=current;syncLabelPreview();renderBarcodeDirectory()}
function syncLabelPreview(){const p=state.products.find(x=>x.id===$('#labelProductSelect')?.value)||state.products[0];if(!p){$('#singleLabelPreview').innerHTML='<div class="empty-state">Add a product first</div>';return}$('#labelBarcode').value=p.sku;$('#singleLabelPreview').innerHTML=productTagHTML(p);drawBarcodes($('#singleLabelPreview'))}
function renderBarcodeDirectory(){const q=($('#barcodeListSearch')?.value||'').toLowerCase();const rows=state.products.filter(p=>`${p.name} ${p.sku}`.toLowerCase().includes(q));$('#barcodeDirectory').innerHTML=rows.map(p=>`<div class="barcode-card"><svg class="barcode-svg" data-code="${p.sku}"></svg><div><strong>${p.name}</strong><small>${p.sku}</small><button class="text-btn" data-dir-label="${p.id}">Print label</button></div></div>`).join('')||'<div class="empty-state">No products</div>';drawBarcodes($('#barcodeDirectory'));$$('[data-dir-label]').forEach(b=>b.onclick=()=>printLabels([state.products.find(p=>p.id===b.dataset.dirLabel)],1,$('#labelSize').value))}
function printLabels(products,qty=1,size='40x25'){const area=$('#barcodePrintArea');area.className=`barcode-print-area size-${size}`;area.innerHTML=products.flatMap(p=>Array.from({length:qty},()=>productTagHTML(p))).join('');drawBarcodes(area);document.body.classList.add('barcode-printing');setTimeout(()=>window.print(),150);setTimeout(()=>document.body.classList.remove('barcode-printing'),1000)}
function renderSettings(){const s=state.settings;$('#settingStoreName').value=s.storeName;$('#settingPhone').value=s.phone;$('#settingAddress').value=s.address;$('#settingFooter').value=s.footer;$('#settingPrinter').value=s.printer}$('#saveSettings').onclick=async()=>{try{requireAdmin();state.settings={storeName:$('#settingStoreName').value.trim()||'KB LABEL',phone:$('#settingPhone').value.trim(),address:$('#settingAddress').value.trim(),footer:$('#settingFooter').value.trim(),printer:$('#settingPrinter').value};await setDoc(doc(db,'settings','pos'),{...state.settings,updatedAt:serverTimestamp()},{merge:true});toast('Settings saved to Firebase')}catch(e){toast(e.message,'error')}};
function download(filename,text,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=filename;a.click();URL.revokeObjectURL(a.href)}function csvEscape(v){return `"${String(v??'').replaceAll('"','""')}"`}$('#exportProductsBtn').onclick=()=>{const h=['name','sku','category','size','color','price','cost','stock','image','description'];download('kb-label-products.csv',[h.join(','),...state.products.map(p=>h.map(k=>csvEscape(p[k])).join(','))].join('\n'),'text/csv')};$('#exportSalesBtn').onclick=()=>{const h=['receipt','date','customerName','customerPhone','payment','subtotal','discount','total','items'];download('kb-label-sales.csv',[h.join(','),...state.sales.map(s=>[s.receipt,s.date,s.customerName,s.customerPhone,s.payment,s.subtotal,s.discount,s.total,(s.items||[]).map(i=>`${i.name} x${i.qty}`).join(' | ')].map(csvEscape).join(','))].join('\n'),'text/csv')};const backup=()=>download(`kb-label-cloud-backup-${todayKey()}.json`,JSON.stringify(state,null,2));$('#downloadBackup').onclick=backup;$('#quickBackup').onclick=backup;$('#restoreBackupBtn').onclick=()=>toast('Cloud restore is disabled for safety. Use CSV import.','error');$('#resetAllData').onclick=()=>toast('Cloud reset is disabled for safety.','error');$('#importCsvBtn').onclick=()=>toast('Use Add Product or existing KB admin product uploader.','error');

$('#generateProductBarcode').onclick=()=>{$('#productSku').value=generateBarcode();toast('Unique barcode generated')};
$('#labelProductSelect').onchange=syncLabelPreview;$('#barcodeListSearch').oninput=renderBarcodeDirectory;
$('#regenerateBarcodeBtn').onclick=async()=>{const p=state.products.find(x=>x.id===$('#labelProductSelect').value);if(!p)return;const code=generateBarcode();await setDoc(doc(db,'products',p.id),{sku:code,barcode:code,updatedAt:serverTimestamp()},{merge:true});toast('New barcode saved')};
$('#printBarcodeLabelsBtn').onclick=()=>{const p=state.products.find(x=>x.id===$('#labelProductSelect').value);if(p)printLabels([p],Math.max(1,Number($('#labelQuantity').value||1)),$('#labelSize').value)};
$('#openQuickBarcodeProduct').onclick=()=>{openProductModal();$('#productSku').value=generateBarcode()};
$('#selectAllProducts').onchange=e=>$$('.product-label-check').forEach(c=>c.checked=e.target.checked);
$('#printSelectedLabelsBtn').onclick=()=>{const ids=$$('.product-label-check:checked').map(c=>c.value);if(!ids.length)return toast('Select products first','error');printLabels(state.products.filter(p=>ids.includes(p.id)),1,'40x25')};
let scanBuffer='',scanTimer;document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)&&document.activeElement?.id!=='barcodeInput')return;if(e.key==='Enter'&&scanBuffer){handleBarcode(scanBuffer);scanBuffer='';return}if(e.key.length===1){scanBuffer+=e.key;clearTimeout(scanTimer);scanTimer=setTimeout(()=>scanBuffer='',180)}});
function handleBarcode(code){const clean=String(code).trim();const p=state.products.find(x=>String(x.sku).trim()===clean);if(!p)return toast(`Barcode not found: ${clean}`,'error');addToCart(p.id);$('#barcodeInput').value='';switchView('pos')}
$('#barcodeInput').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();handleBarcode(e.currentTarget.value)}});
let html5Scanner=null;$('#cameraScanBtn').onclick=async()=>{try{$('#scannerModal').classList.add('open');html5Scanner=new Html5Qrcode('cameraReader');await html5Scanner.start({facingMode:'environment'},{fps:10,qrbox:{width:280,height:150}},async code=>{handleBarcode(code);if(!$('#continuousCamera')?.checked)await closeCamera()},()=>{})}catch(e){toast('Camera could not start. Check permission/HTTPS.','error')}};
async function closeCamera(){try{if(html5Scanner){await html5Scanner.stop();await html5Scanner.clear();html5Scanner=null}}catch(e){}$('#scannerModal').classList.remove('open')}$('#closeScanner').onclick=closeCamera;
$('#posLogout').onclick=async()=>{await signOut(auth);sessionStorage.removeItem('unifiedAdmin');location.replace('admin-login.html?next=pos.html')};
document.addEventListener('keydown',e=>{if(e.key==='F2'){e.preventDefault();switchView('pos');$('#barcodeInput')?.focus()}if(e.key==='F9'){e.preventDefault();$('#completeSale')?.click()}if(e.key==='Escape'&&document.activeElement?.id==='posSearch'){$('#posSearch').value='';renderPOS()}if(e.key==='Enter'&&$('#cashModal')?.classList.contains('open')&&document.activeElement?.id==='cashModalReceived'){e.preventDefault();$('#confirmCashSale').click()}});
$$('[data-quick]').forEach(b=>b.onclick=()=>{$$('[data-quick]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const mode=b.dataset.quick;if(mode==='low'){$('#posSearch').value='';activeCategory='All';const ids=new Set(state.products.filter(p=>p.stock<=5).map(p=>p.id));renderPOS();$$('[data-add-product]').forEach(c=>c.style.display=ids.has(c.dataset.addProduct)?'':'none')}else{renderPOS()}});
window.addEventListener('load',()=>setTimeout(()=>$('#barcodeInput')?.focus(),500));
function tick(){$('#liveClock').textContent=new Date().toLocaleString('en-LK',{dateStyle:'medium',timeStyle:'short'})}setInterval(tick,1000);tick();
onAuthStateChanged(auth,user=>{if(!user){location.replace('admin-login.html?next=pos.html');return}if(user.email?.toLowerCase()!==ADMIN_EMAIL.toLowerCase()){toast('Unauthorized account','error');return}onSnapshot(collection(db,'products'),snap=>{state.products=snap.docs.map(normalizeProduct).sort((a,b)=>a.name.localeCompare(b.name));renderDashboard();renderPOS();renderProducts();renderBarcodes()});onSnapshot(query(collection(db,'posSales'),orderBy('createdAt','desc')),snap=>{state.sales=snap.docs.map(normalizeSale);renderDashboard();renderSales();renderReports()},e=>{console.warn(e);onSnapshot(collection(db,'posSales'),snap=>{state.sales=snap.docs.map(normalizeSale);renderDashboard();renderSales();renderReports()})});onSnapshot(doc(db,'settings','pos'),snap=>{if(snap.exists())state.settings={...state.settings,...snap.data()};renderSettings()});ready=true;renderDashboard()});
